name: Deploy to Docker Hub

on:
  push:
    tags:
      - "*"

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - uses: docker/build-push-action@v1
        id: buildDocker
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: capra314cabra/llvm-alpine
          tags: ${{ steps.tagName.outputs.tag }}
          push: true
