name: Deploy to Docker Hub

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        llvm-version: [8.0.1, 9.0.1, 10.0.0]

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        id: buildDocker
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: capra314cabra/llvm-alpine
          tag_with_ref: true
          build_args: --memory=4g LLVM_FILE_VERSION=${{ matrix.llvm-version }}