name: Deploy to Docker Hub

on:
  push:
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        id: buildDocker
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: capra314cabra/llvm-alpine
          tag_with_ref: true
          build_args: --memory=4g