name: Deploy LLVM 10.0.0 to Docker Hub

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        id: buildDocker
        with:
          username: capra314cabra
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: capra314cabra/llvm-alpine
          tags: ${{ matrix.llvm-version }}
          build_args: LLVM_FILE_VERSION=10.0.0,--memory=4g