name: Deploy LLVM 8.0.1

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        id: build_full
        with:
          username: capra314cabra
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: capra314cabra/llvm-alpine
          tags: "8.0.1"
          path: ./llvm-alpine
          build_args: LLVM_FILE_VERSION=8.0.1
      - uses: docker/build-push-action@v1
        id: build_libs_only
        with:
          username: capra314cabra
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: capra314cabra/llvm-alpine-libs
          tags: "8.0.1"
          path: ./llvm-alpine-libs
          build_args: LLVM_FILE_VERSION=8.0.1