name: Deploy LLVM 9.0.1

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        id: buildDocker
        with:
          username: capra314cabra
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: capra314cabra/llvm-alpine
          tags: "9.0.1"
          build_args: LLVM_FILE_VERSION=9.0.1,--memory=4g